# Generated by Django 2.1.1 on 2018-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0008_auto_20180922_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
