# Generated by Django 2.1.1 on 2018-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0009_auto_20180922_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
