# Generated by Django 2.1.1 on 2018-09-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_auto_20180922_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qoute',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
