# Generated by Django 2.1.1 on 2018-09-25 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0016_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userkhan',
        ),
        migrations.RenameField(
            model_name='userkhan',
            old_name='email',
            new_name='hisemail',
        ),
        migrations.RenameField(
            model_name='userkhan',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='userkhan',
            old_name='password',
            new_name='userpassword',
        ),
    ]
