# Generated by Django 2.1.1 on 2018-09-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0018_auto_20180925_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoute',
            name='created_at',
        ),
    ]
