# Generated by Django 2.1.1 on 2018-09-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0022_auto_20180925_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qoute',
            name='picture',
        ),
    ]
