# Generated by Django 2.1.1 on 2018-09-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0023_remove_qoute_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkhan',
            name='hisemail',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
