# Generated by Django 2.1.1 on 2018-09-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0025_auto_20180927_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkhan',
            name='hisemail',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
