# Generated by Django 2.1.1 on 2018-09-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0026_userkhan_hisemail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userkhan',
            new_name='Quoters',
        ),
    ]
