# Generated by Django 2.1.1 on 2018-09-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0027_auto_20180927_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoters',
            name='hisemail',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
