# Generated by Django 2.1.1 on 2018-09-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0028_auto_20180927_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quoters',
        ),
    ]
